// WARNING: THIS FILE IS AUTOGENERATED! As such, it should not be edited.
// Edits need to be made to the proto files
// (see
// https://github.com/mavlink/MAVSDK-Proto/blob/master/protos/tunnel_server/tunnel_server.proto)

#include <iomanip>

#include "tunnel_server_impl.h"
#include "plugins/tunnel_server/tunnel_server.h"

namespace mavsdk {

using TunnelMessage = TunnelServer::TunnelMessage;

TunnelServer::TunnelServer(std::shared_ptr<ServerComponent> server_component) :
    ServerPluginBase(),
    _impl{std::make_unique<TunnelServerImpl>(server_component)}
{}

TunnelServer::~TunnelServer() {}

TunnelServer::Result TunnelServer::send_tunnel_message(
    uint32_t target_system,
    uint32_t target_component,
    uint32_t payload_type,
    uint32_t payload_length,
    std::vector<std::byte> payload) const
{
    return _impl->send_tunnel_message(
        target_system, target_component, payload_type, payload_length, payload);
}

TunnelServer::TunnelMessageHandle
TunnelServer::subscribe_tunnel_message(const TunnelMessageCallback& callback)
{
    return _impl->subscribe_tunnel_message(callback);
}

void TunnelServer::unsubscribe_tunnel_message(TunnelMessageHandle handle)
{
    _impl->unsubscribe_tunnel_message(handle);
}

bool operator==(const TunnelServer::TunnelMessage& lhs, const TunnelServer::TunnelMessage& rhs)
{
    return (rhs.target_system == lhs.target_system) &&
           (rhs.target_component == lhs.target_component) &&
           (rhs.payload_type == lhs.payload_type) && (rhs.payload_length == lhs.payload_length) &&
           (rhs.payload == lhs.payload);
}

std::ostream& operator<<(std::ostream& str, TunnelServer::TunnelMessage const& tunnel_message)
{
    str << std::setprecision(15);
    str << "tunnel_message:" << '\n' << "{\n";
    str << "    target_system: " << tunnel_message.target_system << '\n';
    str << "    target_component: " << tunnel_message.target_component << '\n';
    str << "    payload_type: " << tunnel_message.payload_type << '\n';
    str << "    payload_length: " << tunnel_message.payload_length << '\n';
    str << "    payload: [";
    for (auto it = tunnel_message.payload.begin(); it != tunnel_message.payload.end(); ++it) {
        str << *it;
        str << (it + 1 != tunnel_message.payload.end() ? ", " : "]\n");
    }
    str << '}';
    return str;
}

std::ostream& operator<<(std::ostream& str, TunnelServer::Result const& result)
{
    switch (result) {
        case TunnelServer::Result::Unknown:
            return str << "Unknown";
        case TunnelServer::Result::Success:
            return str << "Success";
        case TunnelServer::Result::NoSystem:
            return str << "No System";
        case TunnelServer::Result::ConnectionError:
            return str << "Connection Error";
        case TunnelServer::Result::Busy:
            return str << "Busy";
        case TunnelServer::Result::Timeout:
            return str << "Timeout";
        case TunnelServer::Result::InvalidArgument:
            return str << "Invalid Argument";
        case TunnelServer::Result::Unsupported:
            return str << "Unsupported";
        case TunnelServer::Result::Failed:
            return str << "Failed";
        default:
            return str << "Unknown";
    }
}

} // namespace mavsdk