// WARNING: THIS FILE IS AUTOGENERATED! As such, it should not be edited.
// Edits need to be made to the proto files
// (see https://github.com/mavlink/MAVSDK-Proto/blob/master/protos/tunnel/tunnel.proto)

#include <iomanip>

#include "tunnel_impl.h"
#include "plugins/tunnel/tunnel.h"

namespace mavsdk {

using TunnelMessage = Tunnel::TunnelMessage;




Tunnel::Tunnel(System& system) : PluginBase(), _impl{std::make_unique<TunnelImpl>(system)} {}

Tunnel::Tunnel(std::shared_ptr<System> system) : PluginBase(), _impl{std::make_unique<TunnelImpl>(system)} {}


Tunnel::~Tunnel() {}





Tunnel::Result Tunnel::send_tunnel_message(uint32_t target_system, uint32_t target_component, uint32_t payload_type, uint32_t payload_length, std::vector<std::byte> payload) const
{
    return _impl->send_tunnel_message(target_system, target_component, payload_type, payload_length, payload);
}



    
Tunnel::TunnelMessageHandle Tunnel::subscribe_tunnel_message(const TunnelMessageCallback& callback)
{
    return _impl->subscribe_tunnel_message(callback);
}

void Tunnel::unsubscribe_tunnel_message(TunnelMessageHandle handle)
{
    _impl->unsubscribe_tunnel_message(handle);
}
    





bool operator==(const Tunnel::TunnelMessage& lhs, const Tunnel::TunnelMessage& rhs)
{
    return
        (rhs.target_system == lhs.target_system) &&
        (rhs.target_component == lhs.target_component) &&
        (rhs.payload_type == lhs.payload_type) &&
        (rhs.payload_length == lhs.payload_length) &&
        (rhs.payload == lhs.payload);
}

std::ostream& operator<<(std::ostream& str, Tunnel::TunnelMessage const& tunnel_message)
{
    str << std::setprecision(15);
    str << "tunnel_message:" << '\n'
        << "{\n";
    str << "    target_system: " << tunnel_message.target_system << '\n';
    str << "    target_component: " << tunnel_message.target_component << '\n';
    str << "    payload_type: " << tunnel_message.payload_type << '\n';
    str << "    payload_length: " << tunnel_message.payload_length << '\n';
    str << "    payload: [";
    for (auto it = tunnel_message.payload.begin(); it != tunnel_message.payload.end(); ++it) {
        str << *it;
        str << (it + 1 != tunnel_message.payload.end() ? ", " : "]\n");
    }
    str << '}';
    return str;
}



std::ostream& operator<<(std::ostream& str, Tunnel::Result const& result)
{
    switch (result) {
        case Tunnel::Result::Unknown:
            return str << "Unknown";
        case Tunnel::Result::Success:
            return str << "Success";
        case Tunnel::Result::NoSystem:
            return str << "No System";
        case Tunnel::Result::ConnectionError:
            return str << "Connection Error";
        case Tunnel::Result::Busy:
            return str << "Busy";
        case Tunnel::Result::Timeout:
            return str << "Timeout";
        case Tunnel::Result::InvalidArgument:
            return str << "Invalid Argument";
        case Tunnel::Result::Unsupported:
            return str << "Unsupported";
        case Tunnel::Result::Failed:
            return str << "Failed";
        default:
            return str << "Unknown";
    }
}




} // namespace mavsdk