// WARNING: THIS FILE IS AUTOGENERATED! As such, it should not be edited.
// Edits need to be made to the proto files
// (see
// https://github.com/mavlink/MAVSDK-Proto/blob/master/protos/arm_authorizer_server/arm_authorizer_server.proto)

#include "arm_authorizer_server/arm_authorizer_server.grpc.pb.h"
#include "plugins/arm_authorizer_server/arm_authorizer_server.h"

#include "mavsdk.h"

#include "lazy_server_plugin.h"

#include "log.h"
#include <atomic>
#include <cmath>
#include <future>
#include <limits>
#include <memory>
#include <sstream>
#include <vector>

namespace mavsdk {
namespace mavsdk_server {

template<
    typename ArmAuthorizerServer = ArmAuthorizerServer,
    typename LazyServerPlugin = LazyServerPlugin<ArmAuthorizerServer>>

class ArmAuthorizerServerServiceImpl final
    : public rpc::arm_authorizer_server::ArmAuthorizerServerService::Service {
public:
    ArmAuthorizerServerServiceImpl(LazyServerPlugin& lazy_plugin) : _lazy_plugin(lazy_plugin) {}

    static rpc::arm_authorizer_server::CommandAnswer
    translateToRpcCommandAnswer(const mavsdk::ArmAuthorizerServer::CommandAnswer& command_answer)
    {
        switch (command_answer) {
            default:
                LogErr() << "Unknown command_answer enum value: "
                         << static_cast<int>(command_answer);
            // FALLTHROUGH
            case mavsdk::ArmAuthorizerServer::CommandAnswer::Accepted:
                return rpc::arm_authorizer_server::COMMAND_ANSWER_ACCEPTED;
            case mavsdk::ArmAuthorizerServer::CommandAnswer::Failed:
                return rpc::arm_authorizer_server::COMMAND_ANSWER_FAILED;
        }
    }

    static mavsdk::ArmAuthorizerServer::CommandAnswer
    translateFromRpcCommandAnswer(const rpc::arm_authorizer_server::CommandAnswer command_answer)
    {
        switch (command_answer) {
            default:
                LogErr() << "Unknown command_answer enum value: "
                         << static_cast<int>(command_answer);
            // FALLTHROUGH
            case rpc::arm_authorizer_server::COMMAND_ANSWER_ACCEPTED:
                return mavsdk::ArmAuthorizerServer::CommandAnswer::Accepted;
            case rpc::arm_authorizer_server::COMMAND_ANSWER_FAILED:
                return mavsdk::ArmAuthorizerServer::CommandAnswer::Failed;
        }
    }

    static rpc::arm_authorizer_server::RejectionReason translateToRpcRejectionReason(
        const mavsdk::ArmAuthorizerServer::RejectionReason& rejection_reason)
    {
        switch (rejection_reason) {
            default:
                LogErr() << "Unknown rejection_reason enum value: "
                         << static_cast<int>(rejection_reason);
            // FALLTHROUGH
            case mavsdk::ArmAuthorizerServer::RejectionReason::ReasonGeneric:
                return rpc::arm_authorizer_server::REJECTION_REASON_REASON_GENERIC;
            case mavsdk::ArmAuthorizerServer::RejectionReason::ReasonNone:
                return rpc::arm_authorizer_server::REJECTION_REASON_REASON_NONE;
            case mavsdk::ArmAuthorizerServer::RejectionReason::ReasonInvalidWaypoint:
                return rpc::arm_authorizer_server::REJECTION_REASON_REASON_INVALID_WAYPOINT;
            case mavsdk::ArmAuthorizerServer::RejectionReason::ReasonTimeout:
                return rpc::arm_authorizer_server::REJECTION_REASON_REASON_TIMEOUT;
            case mavsdk::ArmAuthorizerServer::RejectionReason::ReasonAirspaceInUse:
                return rpc::arm_authorizer_server::REJECTION_REASON_REASON_AIRSPACE_IN_USE;
            case mavsdk::ArmAuthorizerServer::RejectionReason::ReasonBadWeather:
                return rpc::arm_authorizer_server::REJECTION_REASON_REASON_BAD_WEATHER;
        }
    }

    static mavsdk::ArmAuthorizerServer::RejectionReason translateFromRpcRejectionReason(
        const rpc::arm_authorizer_server::RejectionReason rejection_reason)
    {
        switch (rejection_reason) {
            default:
                LogErr() << "Unknown rejection_reason enum value: "
                         << static_cast<int>(rejection_reason);
            // FALLTHROUGH
            case rpc::arm_authorizer_server::REJECTION_REASON_REASON_GENERIC:
                return mavsdk::ArmAuthorizerServer::RejectionReason::ReasonGeneric;
            case rpc::arm_authorizer_server::REJECTION_REASON_REASON_NONE:
                return mavsdk::ArmAuthorizerServer::RejectionReason::ReasonNone;
            case rpc::arm_authorizer_server::REJECTION_REASON_REASON_INVALID_WAYPOINT:
                return mavsdk::ArmAuthorizerServer::RejectionReason::ReasonInvalidWaypoint;
            case rpc::arm_authorizer_server::REJECTION_REASON_REASON_TIMEOUT:
                return mavsdk::ArmAuthorizerServer::RejectionReason::ReasonTimeout;
            case rpc::arm_authorizer_server::REJECTION_REASON_REASON_AIRSPACE_IN_USE:
                return mavsdk::ArmAuthorizerServer::RejectionReason::ReasonAirspaceInUse;
            case rpc::arm_authorizer_server::REJECTION_REASON_REASON_BAD_WEATHER:
                return mavsdk::ArmAuthorizerServer::RejectionReason::ReasonBadWeather;
        }
    }

    grpc::Status SubscribeArmAuthorization(
        grpc::ServerContext* /* context */,
        const mavsdk::rpc::arm_authorizer_server::SubscribeArmAuthorizationRequest* /* request */,
        grpc::ServerWriter<rpc::arm_authorizer_server::ArmAuthorizationResponse>* writer) override
    {
        if (_lazy_plugin.maybe_plugin() == nullptr) {
            return grpc::Status::OK;
        }

        auto stream_closed_promise = std::make_shared<std::promise<void>>();
        auto stream_closed_future = stream_closed_promise->get_future();
        register_stream_stop_promise(stream_closed_promise);

        auto is_finished = std::make_shared<bool>(false);
        auto subscribe_mutex = std::make_shared<std::mutex>();

        const mavsdk::ArmAuthorizerServer::ArmAuthorizationHandle handle =
            _lazy_plugin.maybe_plugin()->subscribe_arm_authorization(
                [this, &writer, &stream_closed_promise, is_finished, subscribe_mutex, &handle](
                    const uint32_t arm_authorization) {
                    rpc::arm_authorizer_server::ArmAuthorizationResponse rpc_response;

                    rpc_response.set_system_id(arm_authorization);

                    std::unique_lock<std::mutex> lock(*subscribe_mutex);
                    if (!*is_finished && !writer->Write(rpc_response)) {
                        _lazy_plugin.maybe_plugin()->unsubscribe_arm_authorization(handle);

                        *is_finished = true;
                        unregister_stream_stop_promise(stream_closed_promise);
                        stream_closed_promise->set_value();
                    }
                });

        stream_closed_future.wait();
        std::unique_lock<std::mutex> lock(*subscribe_mutex);
        *is_finished = true;

        return grpc::Status::OK;
    }

    grpc::Status AcceptArmAuthorization(
        grpc::ServerContext* /* context */,
        const rpc::arm_authorizer_server::AcceptArmAuthorizationRequest* request,
        rpc::arm_authorizer_server::AcceptArmAuthorizationResponse* response) override
    {
        if (_lazy_plugin.maybe_plugin() == nullptr) {
            return grpc::Status::OK;
        }

        if (request == nullptr) {
            LogWarn() << "AcceptArmAuthorization sent with a null request! Ignoring...";
            return grpc::Status::OK;
        }

        auto result = _lazy_plugin.maybe_plugin()->accept_arm_authorization(request->valid_time());

        if (response != nullptr) {
            response->set_allocated_command_answer(translateToRpcCommandAnswer(result).release());
        }

        return grpc::Status::OK;
    }

    grpc::Status RejectArmAuthorization(
        grpc::ServerContext* /* context */,
        const rpc::arm_authorizer_server::RejectArmAuthorizationRequest* request,
        rpc::arm_authorizer_server::RejectArmAuthorizationResponse* response) override
    {
        if (_lazy_plugin.maybe_plugin() == nullptr) {
            return grpc::Status::OK;
        }

        if (request == nullptr) {
            LogWarn() << "RejectArmAuthorization sent with a null request! Ignoring...";
            return grpc::Status::OK;
        }

        auto result = _lazy_plugin.maybe_plugin()->reject_arm_authorization(
            request->temporarily(),
            translateFromRpcReason(request->reason()),
            request->extra_info());

        if (response != nullptr) {
            response->set_allocated_command_answer(translateToRpcCommandAnswer(result).release());
        }

        return grpc::Status::OK;
    }

    void stop()
    {
        _stopped.store(true);
        for (auto& prom : _stream_stop_promises) {
            if (auto handle = prom.lock()) {
                handle->set_value();
            }
        }
    }

private:
    void register_stream_stop_promise(std::weak_ptr<std::promise<void>> prom)
    {
        // If we have already stopped, set promise immediately and don't add it to list.
        if (_stopped.load()) {
            if (auto handle = prom.lock()) {
                handle->set_value();
            }
        } else {
            _stream_stop_promises.push_back(prom);
        }
    }

    void unregister_stream_stop_promise(std::shared_ptr<std::promise<void>> prom)
    {
        for (auto it = _stream_stop_promises.begin(); it != _stream_stop_promises.end();
             /* ++it */) {
            if (it->lock() == prom) {
                it = _stream_stop_promises.erase(it);
            } else {
                ++it;
            }
        }
    }

    LazyServerPlugin& _lazy_plugin;

    std::atomic<bool> _stopped{false};
    std::vector<std::weak_ptr<std::promise<void>>> _stream_stop_promises{};
};

} // namespace mavsdk_server
} // namespace mavsdk