// WARNING: THIS FILE IS AUTOGENERATED! As such, it should not be edited.
// Edits need to be made to the proto files
// (see https://github.com/mavlink/MAVSDK-Proto/blob/main/protos/tunnel/tunnel.proto)

#pragma once

#include <array>
#include <cmath>
#include <functional>
#include <limits>
#include <memory>
#include <string>
#include <utility>
#include <vector>


#include "plugin_base.h"

#include "handle.h"

namespace mavsdk {


class System;class TunnelImpl;

/**
 * @brief *
 * Allow sending and receiving TUNNEL mavlink messages.
 * 
 * The TUNNEL message allows for arbitrary data to be tunneled through the MAVLink protocol,
 * enabling custom communication between systems.
 */
class Tunnel : public PluginBase {
public:

    /**
     * @brief Constructor. Creates the plugin for a specific System.
     *
     * The plugin is typically created as shown below:
     *
     *     ```cpp
     *     auto tunnel = Tunnel(system);
     *     ```
     *
     * @param system The specific system associated with this plugin.
     */
    explicit Tunnel(System& system); // deprecated

    /**
     * @brief Constructor. Creates the plugin for a specific System.
     *
     * The plugin is typically created as shown below:
     *
     *     ```cpp
     *     auto tunnel = Tunnel(system);
     *     ```
     *
     * @param system The specific system associated with this plugin.
     */
    explicit Tunnel(std::shared_ptr<System> system); // new


    /**
     * @brief Destructor (internal use only).
     */
    ~Tunnel() override;





    /**
     * @brief TUNNEL message data
     */
    struct TunnelMessage {
        
        uint32_t target_system{}; /**< @brief Target system ID (uint8 in mavlink) */
        uint32_t target_component{}; /**< @brief Target component ID (uint8 in mavlink) */
        uint32_t payload_type{}; /**< @brief A code that identifies the content of the tunnel payload (uint16 in mavlink) */
        uint32_t payload_length{}; /**< @brief Length of valid data in payload (uint8 in mavlink, max 128) */
        std::vector<std::byte> payload{}; /**< @brief Fixed 128-byte payload data (32 uint32 values) */
    };

    /**
     * @brief Equal operator to compare two `Tunnel::TunnelMessage` objects.
     *
     * @return `true` if items are equal.
     */
    friend bool operator==(const Tunnel::TunnelMessage& lhs, const Tunnel::TunnelMessage& rhs);

    /**
     * @brief Stream operator to print information about a `Tunnel::TunnelMessage`.
     *
     * @return A reference to the stream.
     */
    friend std::ostream& operator<<(std::ostream& str, Tunnel::TunnelMessage const& tunnel_message);





    /**
     * @brief Possible results returned for tunnel requests.
     */
    enum class Result {
        Unknown, /**< @brief Unknown result. */
        Success, /**< @brief Request was successful. */
        NoSystem, /**< @brief No system is connected. */
        ConnectionError, /**< @brief Connection error. */
        Busy, /**< @brief System is busy. */
        Timeout, /**< @brief Request timed out. */
        InvalidArgument, /**< @brief Invalid argument provided. */
        Unsupported, /**< @brief Operation not supported. */
        Failed, /**< @brief Request failed. */
    };

    /**
     * @brief Stream operator to print information about a `Tunnel::Result`.
     *
     * @return A reference to the stream.
     */
    friend std::ostream& operator<<(std::ostream& str, Tunnel::Result const& result);



    /**
     * @brief Callback type for asynchronous Tunnel calls.
     */
    using ResultCallback = std::function<void(Result)>;






    /**
     * @brief Send a TUNNEL message with custom payload data.
     *
     * This function is blocking.
     *
     * @return Result of request.
     */
    Result send_tunnel_message(uint32_t target_system, uint32_t target_component, uint32_t payload_type, uint32_t payload_length, std::vector<std::byte> payload) const;




        

    /**
     * @brief Callback type for subscribe_tunnel_message.
     */
    using TunnelMessageCallback = std::function<void(TunnelMessage)>;

    /**
     * @brief Handle type for subscribe_tunnel_message.
     */
    using TunnelMessageHandle = Handle<TunnelMessage>;

    /**
     * @brief Subscribe to incoming TUNNEL messages.
     * 
     * This allows registering a callback to receive TUNNEL messages from the vehicle.
     */
    TunnelMessageHandle subscribe_tunnel_message(const TunnelMessageCallback& callback);

    /**
     * @brief Unsubscribe from subscribe_tunnel_message
     */
    void unsubscribe_tunnel_message(TunnelMessageHandle handle);

        






    /**
     * @brief Copy constructor.
     */
    Tunnel(const Tunnel& other);

    /**
     * @brief Equality operator (object is not copyable).
     */
    const Tunnel& operator=(const Tunnel&) = delete;

private:
    /** @private Underlying implementation, set at instantiation */
    std::unique_ptr<TunnelImpl> _impl;
};

} // namespace mavsdk