// WARNING: THIS FILE IS AUTOGENERATED! As such, it should not be edited.
// Edits need to be made to the proto files
// (see https://github.com/mavlink/MAVSDK-Proto/blob/main/protos/command_server/command_server.proto)

#pragma once

#include <array>
#include <cmath>
#include <functional>
#include <limits>
#include <memory>
#include <string>
#include <utility>
#include <vector>


#include "server_plugin_base.h"

#include "handle.h"

namespace mavsdk {


class ServerComponent;
class CommandServerImpl;

/**
 * @brief Provides handling of general MAVLink command interface
 */
class CommandServer : public ServerPluginBase {
public:

    /**
     * @brief Constructor. Creates the plugin for a ServerComponent instance.
     *
     * The plugin is typically created as shown below:
     *
     *     ```cpp
     *     auto command_server = CommandServer(server_component);
     *     ```
     *
     * @param server_component The ServerComponent instance associated with this server plugin.
     */
    explicit CommandServer(std::shared_ptr<ServerComponent> server_component);


    /**
     * @brief Destructor (internal use only).
     */
    ~CommandServer() override;


    /**
     * @brief MAVLink command result following MAV_RESULT enum
     */
    enum class CommandResult {
        Accepted, /**< @brief Command is valid and was executed successfully. */
        TemporarilyRejected, /**< @brief Command is valid but cannot be executed at this time. */
        Denied, /**< @brief Command is invalid or not supported. */
        Unsupported, /**< @brief Command is not supported. */
        Failed, /**< @brief Command is valid but execution has failed. */
        InProgress, /**< @brief Command is being executed. */
        Cancelled, /**< @brief Command has been cancelled. */
        CommandLongOnly, /**< @brief. */
        CommandIntOnly, /**< @brief. */
        CommandUnsupportedMavFrame, /**< @brief. */
    };

    /**
     * @brief Stream operator to print information about a `CommandServer::CommandResult`.
     *
     * @return A reference to the stream.
     */
    friend std::ostream& operator<<(std::ostream& str, CommandServer::CommandResult const& command_result);




    /**
     * @brief MAVLink command structure following MAV_CMD protocol
     */
    struct MavlinkCommand {
        
        uint32_t target_system{}; /**< @brief */
        uint32_t target_component{}; /**< @brief */
        uint32_t command{}; /**< @brief MAVLink command ID (e.g., MAV_CMD_NAV_TAKEOFF) */
        uint32_t confirmation{}; /**< @brief Source system ID */
        float param1{}; /**< @brief Parameter 1 */
        float param2{}; /**< @brief Parameter 2 */
        float param3{}; /**< @brief Parameter 3 */
        float param4{}; /**< @brief Parameter 4 */
        float param5{}; /**< @brief Parameter 5 (x position for location-based commands) */
        float param6{}; /**< @brief Parameter 6 (y position for location-based commands) */
        float param7{}; /**< @brief Parameter 7 (z position for location-based commands) */
    };

    /**
     * @brief Equal operator to compare two `CommandServer::MavlinkCommand` objects.
     *
     * @return `true` if items are equal.
     */
    friend bool operator==(const CommandServer::MavlinkCommand& lhs, const CommandServer::MavlinkCommand& rhs);

    /**
     * @brief Stream operator to print information about a `CommandServer::MavlinkCommand`.
     *
     * @return A reference to the stream.
     */
    friend std::ostream& operator<<(std::ostream& str, CommandServer::MavlinkCommand const& mavlink_command);




    /**
     * @brief Command acknowledgment structure following MAV_RESULT protocol
     */
    struct CommandAck {
        
        uint32_t command{}; /**< @brief MAVLink command that was acknowledged */
        CommandResult result{}; /**< @brief Result of the command */
        uint32_t progress{}; /**< @brief Progress of command execution (0-100, optional) */
        int32_t result_param2{}; /**< @brief Additional result parameter (optional) */
        uint32_t target_system{}; /**< @brief Target system ID */
        uint32_t target_component{}; /**< @brief Target component ID */
    };

    /**
     * @brief Equal operator to compare two `CommandServer::CommandAck` objects.
     *
     * @return `true` if items are equal.
     */
    friend bool operator==(const CommandServer::CommandAck& lhs, const CommandServer::CommandAck& rhs);

    /**
     * @brief Stream operator to print information about a `CommandServer::CommandAck`.
     *
     * @return A reference to the stream.
     */
    friend std::ostream& operator<<(std::ostream& str, CommandServer::CommandAck const& command_ack);





    /**
     * @brief Possible results returned for command server requests
     */
    enum class Result {
        Unknown, /**< @brief Unknown result. */
        Success, /**< @brief Command executed successfully. */
        NoSystem, /**< @brief No system connected. */
        ConnectionError, /**< @brief Connection error. */
        Busy, /**< @brief System is busy. */
        CommandDenied, /**< @brief Command was denied. */
        CommandUnsupported, /**< @brief Command is not supported. */
        Timeout, /**< @brief Command timed out. */
        WrongArgument, /**< @brief Command has wrong argument(s). */
    };

    /**
     * @brief Stream operator to print information about a `CommandServer::Result`.
     *
     * @return A reference to the stream.
     */
    friend std::ostream& operator<<(std::ostream& str, CommandServer::Result const& result);



    /**
     * @brief Callback type for asynchronous CommandServer calls.
     */
    using ResultCallback = std::function<void(Result)>;




        

    /**
     * @brief Callback type for subscribe_command.
     */
    using CommandCallback = std::function<void(MavlinkCommand)>;

    /**
     * @brief Handle type for subscribe_command.
     */
    using CommandHandle = Handle<MavlinkCommand>;

    /**
     * @brief Subscribe to any MAVLink command by command ID. Each request received should respond using RespondCommand.
     */
    CommandHandle subscribe_command(uint32_t command_id, const CommandCallback& callback);

    /**
     * @brief Unsubscribe from subscribe_command
     */
    void unsubscribe_command(CommandHandle handle);

        








    /**
     * @brief Respond to a MAVLink command from SubscribeCommand.
     *
     * This function is blocking.
     *
     * @return Result of request.
     */
    Result respond_command(CommandAck command_ack) const;




    /**
     * @brief Send a MAVLink command to the system.
     *
     * This function is non-blocking.
     */
    void send_command_async(MavlinkCommand command, const ResultCallback callback);








    /**
     * @brief Send a MAVLink command and wait for acknowledgment.
     *
     * This function is blocking.
     *
     * @return Result of request.
     */
    std::pair<Result, CommandServer::CommandAck> send_command_and_wait_for_ack(MavlinkCommand command, float timeout_s) const;




    /**
     * @brief Copy constructor.
     */
    CommandServer(const CommandServer& other);

    /**
     * @brief Equality operator (object is not copyable).
     */
    const CommandServer& operator=(const CommandServer&) = delete;

private:
    /** @private Underlying implementation, set at instantiation */
    std::unique_ptr<CommandServerImpl> _impl;
};

} // namespace mavsdk