// WARNING: THIS FILE IS AUTOGENERATED! As such, it should not be edited.
// Edits need to be made to the proto files
// (see https://github.com/mavlink/MAVSDK-Proto/blob/master/protos/tunnel_server/tunnel_server.proto)

#include "tunnel_server/tunnel_server.grpc.pb.h"
#include "plugins/tunnel_server/tunnel_server.h"

#include "mavsdk.h"

#include "lazy_server_plugin.h"

#include "log.h"
#include <atomic>
#include <cmath>
#include <future>
#include <limits>
#include <memory>
#include <mutex>
#include <sstream>
#include <vector>

namespace mavsdk {
namespace mavsdk_server {


template<typename TunnelServer = TunnelServer, typename LazyServerPlugin = LazyServerPlugin<TunnelServer>>

class TunnelServerServiceImpl final : public rpc::tunnel_server::TunnelServerService::Service {
public:

    TunnelServerServiceImpl(LazyServerPlugin& lazy_plugin) : _lazy_plugin(lazy_plugin) {}



    template<typename ResponseType>
    void fillResponseWithResult(ResponseType* response, mavsdk::TunnelServer::Result& result) const
    {
        auto rpc_result = translateToRpcResult(result);

        auto* rpc_tunnel_server_result = new rpc::tunnel_server::TunnelServerResult();
        rpc_tunnel_server_result->set_result(rpc_result);
        std::stringstream ss;
        ss << result;
        rpc_tunnel_server_result->set_result_str(ss.str());

        response->set_allocated_tunnel_server_result(rpc_tunnel_server_result);
    }




    static std::unique_ptr<rpc::tunnel_server::TunnelMessage> translateToRpcTunnelMessage(const mavsdk::TunnelServer::TunnelMessage &tunnel_message)
    {
        auto rpc_obj = std::make_unique<rpc::tunnel_server::TunnelMessage>();


            
        rpc_obj->set_target_system(tunnel_message.target_system);
            
        
            
        rpc_obj->set_target_component(tunnel_message.target_component);
            
        
            
        rpc_obj->set_payload_type(tunnel_message.payload_type);
            
        
            
        rpc_obj->set_payload_length(tunnel_message.payload_length);
            
        
            
        for (const auto& elem : tunnel_message.payload) {
            rpc_obj->add_payload(elem);
        }
            
        

        return rpc_obj;
    }

    static mavsdk::TunnelServer::TunnelMessage translateFromRpcTunnelMessage(const rpc::tunnel_server::TunnelMessage& tunnel_message)
    {
        mavsdk::TunnelServer::TunnelMessage obj;


            
        obj.target_system = tunnel_message.target_system();
            
        
            
        obj.target_component = tunnel_message.target_component();
            
        
            
        obj.payload_type = tunnel_message.payload_type();
            
        
            
        obj.payload_length = tunnel_message.payload_length();
            
        
            
                for (const auto& elem : tunnel_message.payload()) {
                    obj.payload.push_back(elem);
                }
            
        
        return obj;
    }




    static rpc::tunnel_server::TunnelResult::Result translateToRpcResult(const mavsdk::TunnelServer::Result& result)
    {
        switch (result) {
            default:
                LogErr() << "Unknown result enum value: " << static_cast<int>(result);
            // FALLTHROUGH
            case mavsdk::TunnelServer::Result::Unknown:
                return rpc::tunnel_server::TunnelResult_Result_RESULT_UNKNOWN;
            case mavsdk::TunnelServer::Result::Success:
                return rpc::tunnel_server::TunnelResult_Result_RESULT_SUCCESS;
            case mavsdk::TunnelServer::Result::NoSystem:
                return rpc::tunnel_server::TunnelResult_Result_RESULT_NO_SYSTEM;
            case mavsdk::TunnelServer::Result::ConnectionError:
                return rpc::tunnel_server::TunnelResult_Result_RESULT_CONNECTION_ERROR;
            case mavsdk::TunnelServer::Result::Busy:
                return rpc::tunnel_server::TunnelResult_Result_RESULT_BUSY;
            case mavsdk::TunnelServer::Result::Timeout:
                return rpc::tunnel_server::TunnelResult_Result_RESULT_TIMEOUT;
            case mavsdk::TunnelServer::Result::InvalidArgument:
                return rpc::tunnel_server::TunnelResult_Result_RESULT_INVALID_ARGUMENT;
            case mavsdk::TunnelServer::Result::Unsupported:
                return rpc::tunnel_server::TunnelResult_Result_RESULT_UNSUPPORTED;
            case mavsdk::TunnelServer::Result::Failed:
                return rpc::tunnel_server::TunnelResult_Result_RESULT_FAILED;
        }
    }

    static mavsdk::TunnelServer::Result translateFromRpcResult(const rpc::tunnel_server::TunnelResult::Result result)
    {
        switch (result) {
            default:
                LogErr() << "Unknown result enum value: " << static_cast<int>(result);
            // FALLTHROUGH
            case rpc::tunnel_server::TunnelResult_Result_RESULT_UNKNOWN:
                return mavsdk::TunnelServer::Result::Unknown;
            case rpc::tunnel_server::TunnelResult_Result_RESULT_SUCCESS:
                return mavsdk::TunnelServer::Result::Success;
            case rpc::tunnel_server::TunnelResult_Result_RESULT_NO_SYSTEM:
                return mavsdk::TunnelServer::Result::NoSystem;
            case rpc::tunnel_server::TunnelResult_Result_RESULT_CONNECTION_ERROR:
                return mavsdk::TunnelServer::Result::ConnectionError;
            case rpc::tunnel_server::TunnelResult_Result_RESULT_BUSY:
                return mavsdk::TunnelServer::Result::Busy;
            case rpc::tunnel_server::TunnelResult_Result_RESULT_TIMEOUT:
                return mavsdk::TunnelServer::Result::Timeout;
            case rpc::tunnel_server::TunnelResult_Result_RESULT_INVALID_ARGUMENT:
                return mavsdk::TunnelServer::Result::InvalidArgument;
            case rpc::tunnel_server::TunnelResult_Result_RESULT_UNSUPPORTED:
                return mavsdk::TunnelServer::Result::Unsupported;
            case rpc::tunnel_server::TunnelResult_Result_RESULT_FAILED:
                return mavsdk::TunnelServer::Result::Failed;
        }
    }




    grpc::Status SendTunnelMessage(
        grpc::ServerContext* /* context */,
        const rpc::tunnel_server::SendTunnelMessageRequest* request,
        rpc::tunnel_server::SendTunnelMessageResponse* response) override
    {
        if (_lazy_plugin.maybe_plugin() == nullptr) {
            
            if (response != nullptr) {
                
                // For server plugins, this should never happen, they should always be constructible.
                auto result = mavsdk::TunnelServer::Result::Unknown;
                fillResponseWithResult(response, result);
            }
            
            return grpc::Status::OK;
        }

        if (request == nullptr) {
            LogWarn() << "SendTunnelMessage sent with a null request! Ignoring...";
            return grpc::Status::OK;
        }
            
        
            
        
            
        
            
        
            
        std::vector<mavsdk::TunnelServer::std::byte> payload_vec;
        for (const auto& elem : request->payload()) {
            payload_vec.push_back(elem);
        }
            
        
        auto result = _lazy_plugin.maybe_plugin()->send_tunnel_message(request->target_system(), request->target_component(), request->payload_type(), request->payload_length(), payload_vec);
        

        
        if (response != nullptr) {
            fillResponseWithResult(response, result);
        }
        

        return grpc::Status::OK;
    }

    grpc::Status SubscribeTunnelMessage(grpc::ServerContext* /* context */, const mavsdk::rpc::tunnel_server::SubscribeTunnelMessageRequest* /* request */, grpc::ServerWriter<rpc::tunnel_server::TunnelMessageResponse>* writer) override
    {
        if (_lazy_plugin.maybe_plugin() == nullptr) {
            
            return grpc::Status::OK;
        }

        auto stream_closed_promise = std::make_shared<std::promise<void>>();
        auto stream_closed_future = stream_closed_promise->get_future();
        register_stream_stop_promise(stream_closed_promise);

        auto is_finished = std::make_shared<bool>(false);
        auto subscribe_mutex = std::make_shared<std::mutex>();

        const mavsdk::TunnelServer::TunnelMessageHandle handle = _lazy_plugin.maybe_plugin()->subscribe_tunnel_message(
            [this, &writer, &stream_closed_promise, is_finished, subscribe_mutex, &handle](const mavsdk::TunnelServer::TunnelMessage tunnel_message) {

            rpc::tunnel_server::TunnelMessageResponse rpc_response;
        
            rpc_response.set_allocated_tunnel_message(translateToRpcTunnelMessage(tunnel_message).release());
        

        

            std::unique_lock<std::mutex> lock(*subscribe_mutex);
            if (!*is_finished && !writer->Write(rpc_response)) {
                
                _lazy_plugin.maybe_plugin()->unsubscribe_tunnel_message(handle);
                
                *is_finished = true;
                unregister_stream_stop_promise(stream_closed_promise);
                stream_closed_promise->set_value();
            }
        });

        stream_closed_future.wait();
        std::unique_lock<std::mutex> lock(*subscribe_mutex);
        *is_finished = true;

        return grpc::Status::OK;
    }


    void stop() {
        _stopped.store(true);
        std::lock_guard<std::mutex> lock(_stream_stop_mutex);
        for (auto& prom : _stream_stop_promises) {
            if (auto handle = prom.lock()) {
                handle->set_value();
            }
        }
    }

private:
    void register_stream_stop_promise(std::weak_ptr<std::promise<void>> prom) {
        // If we have already stopped, set promise immediately and don't add it to list.
        if (_stopped.load()) {
            if (auto handle = prom.lock()) {
                handle->set_value();
            }
        } else {
            std::lock_guard<std::mutex> lock(_stream_stop_mutex);
            _stream_stop_promises.push_back(prom);
        }
    }

    void unregister_stream_stop_promise(std::shared_ptr<std::promise<void>> prom) {
        std::lock_guard<std::mutex> lock(_stream_stop_mutex);
        for (auto it = _stream_stop_promises.begin(); it != _stream_stop_promises.end(); /* ++it */) {
            if (it->lock() == prom) {
                it = _stream_stop_promises.erase(it);
            } else {
                ++it;
            }
        }
    }


    LazyServerPlugin& _lazy_plugin;

    std::atomic<bool> _stopped{false};
    std::mutex _stream_stop_mutex{};
    std::vector<std::weak_ptr<std::promise<void>>> _stream_stop_promises {};
};

} // namespace mavsdk_server
} // namespace mavsdk