// WARNING: THIS FILE IS AUTOGENERATED! As such, it should not be edited.
// Edits need to be made to the proto files
// (see https://github.com/mavlink/MAVSDK-Proto/blob/master/protos/command_server/command_server.proto)

#include "command_server/command_server.grpc.pb.h"
#include "plugins/command_server/command_server.h"

#include "mavsdk.h"

#include "lazy_server_plugin.h"

#include "log.h"
#include <atomic>
#include <cmath>
#include <future>
#include <limits>
#include <memory>
#include <mutex>
#include <sstream>
#include <vector>

namespace mavsdk {
namespace mavsdk_server {


template<typename CommandServer = CommandServer, typename LazyServerPlugin = LazyServerPlugin<CommandServer>>

class CommandServerServiceImpl final : public rpc::command_server::CommandServerService::Service {
public:

    CommandServerServiceImpl(LazyServerPlugin& lazy_plugin) : _lazy_plugin(lazy_plugin) {}



    template<typename ResponseType>
    void fillResponseWithResult(ResponseType* response, mavsdk::CommandServer::Result& result) const
    {
        auto rpc_result = translateToRpcResult(result);

        auto* rpc_command_server_result = new rpc::command_server::CommandServerResult();
        rpc_command_server_result->set_result(rpc_result);
        std::stringstream ss;
        ss << result;
        rpc_command_server_result->set_result_str(ss.str());

        response->set_allocated_command_server_result(rpc_command_server_result);
    }


    static rpc::command_server::CommandResult translateToRpcCommandResult(const mavsdk::CommandServer::CommandResult& command_result)
    {
        switch (command_result) {
            default:
                LogErr() << "Unknown command_result enum value: " << static_cast<int>(command_result);
            // FALLTHROUGH
            case mavsdk::CommandServer::CommandResult::Accepted:
                return rpc::command_server::COMMAND_RESULT_ACCEPTED;
            case mavsdk::CommandServer::CommandResult::TemporarilyRejected:
                return rpc::command_server::COMMAND_RESULT_TEMPORARILY_REJECTED;
            case mavsdk::CommandServer::CommandResult::Denied:
                return rpc::command_server::COMMAND_RESULT_DENIED;
            case mavsdk::CommandServer::CommandResult::Unsupported:
                return rpc::command_server::COMMAND_RESULT_UNSUPPORTED;
            case mavsdk::CommandServer::CommandResult::Failed:
                return rpc::command_server::COMMAND_RESULT_FAILED;
            case mavsdk::CommandServer::CommandResult::InProgress:
                return rpc::command_server::COMMAND_RESULT_IN_PROGRESS;
            case mavsdk::CommandServer::CommandResult::Cancelled:
                return rpc::command_server::COMMAND_RESULT_CANCELLED;
            case mavsdk::CommandServer::CommandResult::CommandLongOnly:
                return rpc::command_server::COMMAND_RESULT_COMMAND_LONG_ONLY;
            case mavsdk::CommandServer::CommandResult::CommandIntOnly:
                return rpc::command_server::COMMAND_RESULT_COMMAND_INT_ONLY;
            case mavsdk::CommandServer::CommandResult::CommandUnsupportedMavFrame:
                return rpc::command_server::COMMAND_RESULT_COMMAND_UNSUPPORTED_MAV_FRAME;
        }
    }

    static mavsdk::CommandServer::CommandResult translateFromRpcCommandResult(const rpc::command_server::CommandResult command_result)
    {
        switch (command_result) {
            default:
                LogErr() << "Unknown command_result enum value: " << static_cast<int>(command_result);
            // FALLTHROUGH
            case rpc::command_server::COMMAND_RESULT_ACCEPTED:
                return mavsdk::CommandServer::CommandResult::Accepted;
            case rpc::command_server::COMMAND_RESULT_TEMPORARILY_REJECTED:
                return mavsdk::CommandServer::CommandResult::TemporarilyRejected;
            case rpc::command_server::COMMAND_RESULT_DENIED:
                return mavsdk::CommandServer::CommandResult::Denied;
            case rpc::command_server::COMMAND_RESULT_UNSUPPORTED:
                return mavsdk::CommandServer::CommandResult::Unsupported;
            case rpc::command_server::COMMAND_RESULT_FAILED:
                return mavsdk::CommandServer::CommandResult::Failed;
            case rpc::command_server::COMMAND_RESULT_IN_PROGRESS:
                return mavsdk::CommandServer::CommandResult::InProgress;
            case rpc::command_server::COMMAND_RESULT_CANCELLED:
                return mavsdk::CommandServer::CommandResult::Cancelled;
            case rpc::command_server::COMMAND_RESULT_COMMAND_LONG_ONLY:
                return mavsdk::CommandServer::CommandResult::CommandLongOnly;
            case rpc::command_server::COMMAND_RESULT_COMMAND_INT_ONLY:
                return mavsdk::CommandServer::CommandResult::CommandIntOnly;
            case rpc::command_server::COMMAND_RESULT_COMMAND_UNSUPPORTED_MAV_FRAME:
                return mavsdk::CommandServer::CommandResult::CommandUnsupportedMavFrame;
        }
    }



    static std::unique_ptr<rpc::command_server::MavlinkCommand> translateToRpcMavlinkCommand(const mavsdk::CommandServer::MavlinkCommand &mavlink_command)
    {
        auto rpc_obj = std::make_unique<rpc::command_server::MavlinkCommand>();


            
        rpc_obj->set_target_system(mavlink_command.target_system);
            
        
            
        rpc_obj->set_target_component(mavlink_command.target_component);
            
        
            
        rpc_obj->set_command(mavlink_command.command);
            
        
            
        rpc_obj->set_confirmation(mavlink_command.confirmation);
            
        
            
        rpc_obj->set_param1(mavlink_command.param1);
            
        
            
        rpc_obj->set_param2(mavlink_command.param2);
            
        
            
        rpc_obj->set_param3(mavlink_command.param3);
            
        
            
        rpc_obj->set_param4(mavlink_command.param4);
            
        
            
        rpc_obj->set_param5(mavlink_command.param5);
            
        
            
        rpc_obj->set_param6(mavlink_command.param6);
            
        
            
        rpc_obj->set_param7(mavlink_command.param7);
            
        

        return rpc_obj;
    }

    static mavsdk::CommandServer::MavlinkCommand translateFromRpcMavlinkCommand(const rpc::command_server::MavlinkCommand& mavlink_command)
    {
        mavsdk::CommandServer::MavlinkCommand obj;


            
        obj.target_system = mavlink_command.target_system();
            
        
            
        obj.target_component = mavlink_command.target_component();
            
        
            
        obj.command = mavlink_command.command();
            
        
            
        obj.confirmation = mavlink_command.confirmation();
            
        
            
        obj.param1 = mavlink_command.param1();
            
        
            
        obj.param2 = mavlink_command.param2();
            
        
            
        obj.param3 = mavlink_command.param3();
            
        
            
        obj.param4 = mavlink_command.param4();
            
        
            
        obj.param5 = mavlink_command.param5();
            
        
            
        obj.param6 = mavlink_command.param6();
            
        
            
        obj.param7 = mavlink_command.param7();
            
        
        return obj;
    }





    static std::unique_ptr<rpc::command_server::CommandAck> translateToRpcCommandAck(const mavsdk::CommandServer::CommandAck &command_ack)
    {
        auto rpc_obj = std::make_unique<rpc::command_server::CommandAck>();


            
        rpc_obj->set_command(command_ack.command);
            
        
            
                
        rpc_obj->set_result(translateToRpcCommandResult(command_ack.result));
                
            
        
            
        rpc_obj->set_progress(command_ack.progress);
            
        
            
        rpc_obj->set_result_param2(command_ack.result_param2);
            
        
            
        rpc_obj->set_target_system(command_ack.target_system);
            
        
            
        rpc_obj->set_target_component(command_ack.target_component);
            
        

        return rpc_obj;
    }

    static mavsdk::CommandServer::CommandAck translateFromRpcCommandAck(const rpc::command_server::CommandAck& command_ack)
    {
        mavsdk::CommandServer::CommandAck obj;


            
        obj.command = command_ack.command();
            
        
            
        obj.result = translateFromRpcCommandResult(command_ack.result());
            
        
            
        obj.progress = command_ack.progress();
            
        
            
        obj.result_param2 = command_ack.result_param2();
            
        
            
        obj.target_system = command_ack.target_system();
            
        
            
        obj.target_component = command_ack.target_component();
            
        
        return obj;
    }




    static rpc::command_server::CommandServerResult::Result translateToRpcResult(const mavsdk::CommandServer::Result& result)
    {
        switch (result) {
            default:
                LogErr() << "Unknown result enum value: " << static_cast<int>(result);
            // FALLTHROUGH
            case mavsdk::CommandServer::Result::Unknown:
                return rpc::command_server::CommandServerResult_Result_RESULT_UNKNOWN;
            case mavsdk::CommandServer::Result::Success:
                return rpc::command_server::CommandServerResult_Result_RESULT_SUCCESS;
            case mavsdk::CommandServer::Result::NoSystem:
                return rpc::command_server::CommandServerResult_Result_RESULT_NO_SYSTEM;
            case mavsdk::CommandServer::Result::ConnectionError:
                return rpc::command_server::CommandServerResult_Result_RESULT_CONNECTION_ERROR;
            case mavsdk::CommandServer::Result::Busy:
                return rpc::command_server::CommandServerResult_Result_RESULT_BUSY;
            case mavsdk::CommandServer::Result::CommandDenied:
                return rpc::command_server::CommandServerResult_Result_RESULT_COMMAND_DENIED;
            case mavsdk::CommandServer::Result::CommandUnsupported:
                return rpc::command_server::CommandServerResult_Result_RESULT_COMMAND_UNSUPPORTED;
            case mavsdk::CommandServer::Result::Timeout:
                return rpc::command_server::CommandServerResult_Result_RESULT_TIMEOUT;
            case mavsdk::CommandServer::Result::WrongArgument:
                return rpc::command_server::CommandServerResult_Result_RESULT_WRONG_ARGUMENT;
        }
    }

    static mavsdk::CommandServer::Result translateFromRpcResult(const rpc::command_server::CommandServerResult::Result result)
    {
        switch (result) {
            default:
                LogErr() << "Unknown result enum value: " << static_cast<int>(result);
            // FALLTHROUGH
            case rpc::command_server::CommandServerResult_Result_RESULT_UNKNOWN:
                return mavsdk::CommandServer::Result::Unknown;
            case rpc::command_server::CommandServerResult_Result_RESULT_SUCCESS:
                return mavsdk::CommandServer::Result::Success;
            case rpc::command_server::CommandServerResult_Result_RESULT_NO_SYSTEM:
                return mavsdk::CommandServer::Result::NoSystem;
            case rpc::command_server::CommandServerResult_Result_RESULT_CONNECTION_ERROR:
                return mavsdk::CommandServer::Result::ConnectionError;
            case rpc::command_server::CommandServerResult_Result_RESULT_BUSY:
                return mavsdk::CommandServer::Result::Busy;
            case rpc::command_server::CommandServerResult_Result_RESULT_COMMAND_DENIED:
                return mavsdk::CommandServer::Result::CommandDenied;
            case rpc::command_server::CommandServerResult_Result_RESULT_COMMAND_UNSUPPORTED:
                return mavsdk::CommandServer::Result::CommandUnsupported;
            case rpc::command_server::CommandServerResult_Result_RESULT_TIMEOUT:
                return mavsdk::CommandServer::Result::Timeout;
            case rpc::command_server::CommandServerResult_Result_RESULT_WRONG_ARGUMENT:
                return mavsdk::CommandServer::Result::WrongArgument;
        }
    }




    grpc::Status SubscribeCommand(grpc::ServerContext* /* context */, const mavsdk::rpc::command_server::SubscribeCommandRequest* request, grpc::ServerWriter<rpc::command_server::CommandResponse>* writer) override
    {
        if (_lazy_plugin.maybe_plugin() == nullptr) {
            
            return grpc::Status::OK;
        }

        auto stream_closed_promise = std::make_shared<std::promise<void>>();
        auto stream_closed_future = stream_closed_promise->get_future();
        register_stream_stop_promise(stream_closed_promise);

        auto is_finished = std::make_shared<bool>(false);
        auto subscribe_mutex = std::make_shared<std::mutex>();

        const mavsdk::CommandServer::CommandHandle handle = _lazy_plugin.maybe_plugin()->subscribe_command(request->command_id(), 
            [this, &writer, &stream_closed_promise, is_finished, subscribe_mutex, &handle](const mavsdk::CommandServer::MavlinkCommand command) {

            rpc::command_server::CommandResponse rpc_response;
        
            rpc_response.set_allocated_result(translateToRpcMavlinkCommand(command).release());
        

        

            std::unique_lock<std::mutex> lock(*subscribe_mutex);
            if (!*is_finished && !writer->Write(rpc_response)) {
                
                _lazy_plugin.maybe_plugin()->unsubscribe_command(handle);
                
                *is_finished = true;
                unregister_stream_stop_promise(stream_closed_promise);
                stream_closed_promise->set_value();
            }
        });

        stream_closed_future.wait();
        std::unique_lock<std::mutex> lock(*subscribe_mutex);
        *is_finished = true;

        return grpc::Status::OK;
    }

    grpc::Status RespondCommand(
        grpc::ServerContext* /* context */,
        const rpc::command_server::RespondCommandRequest* request,
        rpc::command_server::RespondCommandResponse* response) override
    {
        if (_lazy_plugin.maybe_plugin() == nullptr) {
            
            if (response != nullptr) {
                
                // For server plugins, this should never happen, they should always be constructible.
                auto result = mavsdk::CommandServer::Result::Unknown;
                fillResponseWithResult(response, result);
            }
            
            return grpc::Status::OK;
        }

        if (request == nullptr) {
            LogWarn() << "RespondCommand sent with a null request! Ignoring...";
            return grpc::Status::OK;
        }
            
        
        auto result = _lazy_plugin.maybe_plugin()->respond_command(translateFromRpcCommandAck(request->command_ack()));
        

        
        if (response != nullptr) {
            fillResponseWithResult(response, result);
        }
        

        return grpc::Status::OK;
    }

    grpc::Status SendCommand(
        grpc::ServerContext* /* context */,
        const rpc::command_server::SendCommandRequest* request,
        rpc::command_server::SendCommandResponse* response) override
    {
        if (_lazy_plugin.maybe_plugin() == nullptr) {
            
            if (response != nullptr) {
                
                // For server plugins, this should never happen, they should always be constructible.
                auto result = mavsdk::CommandServer::Result::Unknown;
                fillResponseWithResult(response, result);
            }
            
            return grpc::Status::OK;
        }

        if (request == nullptr) {
            LogWarn() << "SendCommand sent with a null request! Ignoring...";
            return grpc::Status::OK;
        }
            
        
        std::promise<mavsdk::CommandServer::Result> prom;
        std::future<mavsdk::CommandServer::Result> fut = prom.get_future();

            
        _lazy_plugin.maybe_plugin()->send_command_async([&prom](const mavsdk::CommandServer::Result result){ prom.set_value(result); });
        auto result = fut.get();
            
        

        
        if (response != nullptr) {
            fillResponseWithResult(response, result);
        }
        

        return grpc::Status::OK;
    }

    grpc::Status SendCommandAndWaitForAck(
        grpc::ServerContext* /* context */,
        const rpc::command_server::SendCommandAndWaitForAckRequest* request,
        rpc::command_server::SendCommandAndWaitForAckResponse* response) override
    {
        if (_lazy_plugin.maybe_plugin() == nullptr) {
            
            if (response != nullptr) {
                
                // For server plugins, this should never happen, they should always be constructible.
                auto result = mavsdk::CommandServer::Result::Unknown;
                fillResponseWithResult(response, result);
            }
            
            return grpc::Status::OK;
        }

        if (request == nullptr) {
            LogWarn() << "SendCommandAndWaitForAck sent with a null request! Ignoring...";
            return grpc::Status::OK;
        }

        auto result = _lazy_plugin.maybe_plugin()->send_command_and_wait_for_ack(translateFromRpcCommand(request->command()), request->timeout_s());

        if (response != nullptr) {
            fillResponseWithResult(response, result.first);
            
            response->set_allocated_command_ack(translateToRpcCommandAck(result.second).release());
            
        }


        return grpc::Status::OK;
    }


    void stop() {
        _stopped.store(true);
        std::lock_guard<std::mutex> lock(_stream_stop_mutex);
        for (auto& prom : _stream_stop_promises) {
            if (auto handle = prom.lock()) {
                handle->set_value();
            }
        }
    }

private:
    void register_stream_stop_promise(std::weak_ptr<std::promise<void>> prom) {
        // If we have already stopped, set promise immediately and don't add it to list.
        if (_stopped.load()) {
            if (auto handle = prom.lock()) {
                handle->set_value();
            }
        } else {
            std::lock_guard<std::mutex> lock(_stream_stop_mutex);
            _stream_stop_promises.push_back(prom);
        }
    }

    void unregister_stream_stop_promise(std::shared_ptr<std::promise<void>> prom) {
        std::lock_guard<std::mutex> lock(_stream_stop_mutex);
        for (auto it = _stream_stop_promises.begin(); it != _stream_stop_promises.end(); /* ++it */) {
            if (it->lock() == prom) {
                it = _stream_stop_promises.erase(it);
            } else {
                ++it;
            }
        }
    }


    LazyServerPlugin& _lazy_plugin;

    std::atomic<bool> _stopped{false};
    std::mutex _stream_stop_mutex{};
    std::vector<std::weak_ptr<std::promise<void>>> _stream_stop_promises {};
};

} // namespace mavsdk_server
} // namespace mavsdk