// WARNING: THIS FILE IS AUTOGENERATED! As such, it should not be edited.
// Edits need to be made to the proto files
// (see https://github.com/mavlink/MAVSDK-Proto/blob/master/protos/command_server/command_server.proto)

#include <iomanip>

#include "command_server_impl.h"
#include "plugins/command_server/command_server.h"

namespace mavsdk {

using MavlinkCommand = CommandServer::MavlinkCommand;
using CommandAck = CommandServer::CommandAck;




CommandServer::CommandServer(std::shared_ptr<ServerComponent> server_component) : ServerPluginBase(), _impl{std::make_unique<CommandServerImpl>(server_component)} {}


CommandServer::~CommandServer() {}



    
CommandServer::CommandHandle CommandServer::subscribe_command(uint32_t command_id, const CommandCallback& callback)
{
    return _impl->subscribe_command(command_id, callback);
}

void CommandServer::unsubscribe_command(CommandHandle handle)
{
    _impl->unsubscribe_command(handle);
}
    







CommandServer::Result CommandServer::respond_command(CommandAck command_ack) const
{
    return _impl->respond_command(command_ack);
}



void CommandServer::send_command_async(MavlinkCommand command, const ResultCallback callback)
{
    _impl->send_command_async(command, callback);
}







std::pair<CommandServer::Result, CommandServer::CommandAck> CommandServer::send_command_and_wait_for_ack(MavlinkCommand command, float timeout_s) const
{
    return _impl->send_command_and_wait_for_ack(command, timeout_s);
}



bool operator==(const CommandServer::MavlinkCommand& lhs, const CommandServer::MavlinkCommand& rhs)
{
    return
        (rhs.target_system == lhs.target_system) &&
        (rhs.target_component == lhs.target_component) &&
        (rhs.command == lhs.command) &&
        (rhs.confirmation == lhs.confirmation) &&
        ((std::isnan(rhs.param1) && std::isnan(lhs.param1)) || rhs.param1 == lhs.param1) &&
        ((std::isnan(rhs.param2) && std::isnan(lhs.param2)) || rhs.param2 == lhs.param2) &&
        ((std::isnan(rhs.param3) && std::isnan(lhs.param3)) || rhs.param3 == lhs.param3) &&
        ((std::isnan(rhs.param4) && std::isnan(lhs.param4)) || rhs.param4 == lhs.param4) &&
        ((std::isnan(rhs.param5) && std::isnan(lhs.param5)) || rhs.param5 == lhs.param5) &&
        ((std::isnan(rhs.param6) && std::isnan(lhs.param6)) || rhs.param6 == lhs.param6) &&
        ((std::isnan(rhs.param7) && std::isnan(lhs.param7)) || rhs.param7 == lhs.param7);
}

std::ostream& operator<<(std::ostream& str, CommandServer::MavlinkCommand const& mavlink_command)
{
    str << std::setprecision(15);
    str << "mavlink_command:" << '\n'
        << "{\n";
    str << "    target_system: " << mavlink_command.target_system << '\n';
    str << "    target_component: " << mavlink_command.target_component << '\n';
    str << "    command: " << mavlink_command.command << '\n';
    str << "    confirmation: " << mavlink_command.confirmation << '\n';
    str << "    param1: " << mavlink_command.param1 << '\n';
    str << "    param2: " << mavlink_command.param2 << '\n';
    str << "    param3: " << mavlink_command.param3 << '\n';
    str << "    param4: " << mavlink_command.param4 << '\n';
    str << "    param5: " << mavlink_command.param5 << '\n';
    str << "    param6: " << mavlink_command.param6 << '\n';
    str << "    param7: " << mavlink_command.param7 << '\n';
    str << '}';
    return str;
}


bool operator==(const CommandServer::CommandAck& lhs, const CommandServer::CommandAck& rhs)
{
    return
        (rhs.command == lhs.command) &&
        (rhs.result == lhs.result) &&
        (rhs.progress == lhs.progress) &&
        (rhs.result_param2 == lhs.result_param2) &&
        (rhs.target_system == lhs.target_system) &&
        (rhs.target_component == lhs.target_component);
}

std::ostream& operator<<(std::ostream& str, CommandServer::CommandAck const& command_ack)
{
    str << std::setprecision(15);
    str << "command_ack:" << '\n'
        << "{\n";
    str << "    command: " << command_ack.command << '\n';
    str << "    result: " << command_ack.result << '\n';
    str << "    progress: " << command_ack.progress << '\n';
    str << "    result_param2: " << command_ack.result_param2 << '\n';
    str << "    target_system: " << command_ack.target_system << '\n';
    str << "    target_component: " << command_ack.target_component << '\n';
    str << '}';
    return str;
}



std::ostream& operator<<(std::ostream& str, CommandServer::Result const& result)
{
    switch (result) {
        case CommandServer::Result::Unknown:
            return str << "Unknown";
        case CommandServer::Result::Success:
            return str << "Success";
        case CommandServer::Result::NoSystem:
            return str << "No System";
        case CommandServer::Result::ConnectionError:
            return str << "Connection Error";
        case CommandServer::Result::Busy:
            return str << "Busy";
        case CommandServer::Result::CommandDenied:
            return str << "Command Denied";
        case CommandServer::Result::CommandUnsupported:
            return str << "Command Unsupported";
        case CommandServer::Result::Timeout:
            return str << "Timeout";
        case CommandServer::Result::WrongArgument:
            return str << "Wrong Argument";
        default:
            return str << "Unknown";
    }
}



std::ostream& operator<<(std::ostream& str, CommandServer::CommandResult const& command_result)
{
    switch (command_result) {
        case CommandServer::CommandResult::Accepted:
            return str << "Accepted";
        case CommandServer::CommandResult::TemporarilyRejected:
            return str << "Temporarily Rejected";
        case CommandServer::CommandResult::Denied:
            return str << "Denied";
        case CommandServer::CommandResult::Unsupported:
            return str << "Unsupported";
        case CommandServer::CommandResult::Failed:
            return str << "Failed";
        case CommandServer::CommandResult::InProgress:
            return str << "In Progress";
        case CommandServer::CommandResult::Cancelled:
            return str << "Cancelled";
        case CommandServer::CommandResult::CommandLongOnly:
            return str << "Command Long Only";
        case CommandServer::CommandResult::CommandIntOnly:
            return str << "Command Int Only";
        case CommandServer::CommandResult::CommandUnsupportedMavFrame:
            return str << "Command Unsupported Mav Frame";
        default:
            return str << "Unknown";
    }
}


} // namespace mavsdk